### ISSUE TITLE
Nice use of variables and variable names

### ISSUE THREAD

**Issue by Caealana** [albert-kevin/intro-data-capstone-musclehub#3]
https://github.com/albert-kevin/intro-data-capstone-musclehub/blob/228804768101138ce967fa2406431054b4ef1f63/albert_kevin/Albert_Kevin_MuscleHub_feb-2018.py#L102-L108

Your variable names are descriptive and helpful for those who are reading your project. Nice use of variables to save the contents of the different data frames so that you can access them easily.

**Comment by albert-kevin** [comment]
I preferred to use DataFrames for a moment because I felt more at home this way to mangle the data if needed.
These variable names are of no use further down the line, but left it for my own understanding.
Interesting to see how one can collaborate on github by masking a code snippet and have a discussion about.

Would you suggest me to follow the standalone SQL course on codecademy in the future ?

PS: I assume you may close this issue ?

**Comment by albert-kevin** [comment]
I will do the SQL course in the future
