### ISSUE TITLE
Correct Join

### ISSUE THREAD

**Issue by Caealana** [albert-kevin/intro-data-capstone-musclehub#4]
https://github.com/albert-kevin/intro-data-capstone-musclehub/blob/228804768101138ce967fa2406431054b4ef1f63/albert_kevin/Albert_Kevin_MuscleHub_feb-2018.py#L134-L183

Nice job -Your joins here are correct. Your resulting table includes some extraneous columns (gender and email) that are not needed for the data analysis in this assignment.

Here is an alternate way to write the joins for your reference:
```
df = sql_query('''
SELECT visits.first_name,
       visits.last_name,
       visits.visit_date,
       fitness_tests.fitness_test_date,
       applications.application_date,
       purchases.purchase_date
FROM visits
LEFT JOIN fitness_tests
    ON fitness_tests.first_name = visits.first_name
    AND fitness_tests.last_name = visits.last_name
    AND fitness_tests.email = visits.email
LEFT JOIN applications
    ON applications.first_name = visits.first_name
    AND applications.last_name = visits.last_name
    AND applications.email = visits.email
LEFT JOIN purchases
    ON purchases.first_name = visits.first_name
    AND purchases.last_name = visits.last_name
    AND purchases.email = visits.email
WHERE visits.visit_date >= '7-1-17'
''')
```

**Comment by albert-kevin** [comment]
I had trouble using the LEFT JOIN command,
I then tried to use WITH and that worked well.
Later I found how to use LEFT JOIN in a cascading manner, I thought at first it was not possible
I left it this way to show you, I prefer the more elegant way like you suggest...

I noticed too in the answers notebook to not use the columns gender and email,
but I left them because the notebook comments suggested to use them.

Would you like me to change this code or leave ?
